report.py: fix crash on get_sched_mode
Current shader-db master report.py reports this for non-intel drivers:

Traceback (most recent call last):
  File "./report.py", line 384, in <module>
    main()
  File "./report.py", line 243, in main
    get_sched_mode(before[p], after[p]))
  File "./report.py", line 114, in get_sched_mode
    p = " (scheduled: " + b["scheduled"]
KeyError: 'scheduled'

Add a check so it avoids accessing the 'scheduled' key when it isn't
valid.

Fixes: 95e35b3 report.py: Handle scheduler mode changes

Signed-off-by: Erico Nunes <nunes.erico@gmail.com>
Reviewed-by: Ian Romanick <ian.d.romanick@intel.com>